### PR TITLE
Finding the nearest integer to the square root of a number

### PR DESCRIPTION
**Pull request by RishiPrakash**
Finding the nearest integer to the square root of a number

### CODE REVIEW

**Comment by RishiPrakash** [comment]
Can anyone help what went wrong here?

**Comment by RishiPrakash** [comment]
I have adeed one more program to compute GCD of 2 numbers also

**Comment by Kyle-P** [comment]
This looks great @RishiPrakash! I'm just going to change up some formatting and merge your code. Thanks for your contributions!

**Comment by Kyle-P** [comment]
Thanks again @RishiPrakash!

**Comment by RishiPrakash** [comment]
It's always great to see to see your pull request merged 😄 Thanks a lot buddy @Kyle-P , looking forward to add more ideas and more programs over the next few weekends

**Pull request merged**
