### PR TITLE
Trigonometric functions

### PR DESCRIPTION
**Pull request by mayokunthefirst**
Adds basic functions

Closes part of https://github.com/Kyle-P/Mathematics/issues/34

### CODE REVIEW

**Comment by Kyle-P** [comment]
Hi @mayokunthefirst! Thanks for tackling this one! The sine, cosine, and tangent functions look great. However, the sineh, cosh, tanh, arcsine, arccosine, and arctan functions don't seem to output the correct answers.

For sineh, cosh, and tanh, the programs seems to be returning values for sin, cos, and tan rather than the sineh, cosh, and tanh function calculations.

For the inverse functions (arcsine, arccosine, arctangent), remember that the input is not an angle, but rather a number that is the result of calculating sine, cosine, or tangent on an angle. These functions aren't returning the correct output in the program.

Feel free to make some edits yourself, or we could post this up in the repo for some more contributors to tackle. Whatever you're comfortable with.

Thanks so much for contributing to our repo! It's very appreciated.

**Comment by mayokunthefirst** [comment]
@Kyle-P i'll take a look at it again but for now you can post it after which i will re-edit

**Comment by Kyle-P** [comment]
Hi @mayokunthefirst. Alright. I'll merge it and raise an issue for this.

**Comment by mayokunthefirst** [comment]
@Kyle-P ,i'll fix it right away

**Pull request merged**
