### PR TITLE
Pythagorean Calculator: Add files via upload

### PR DESCRIPTION
**Pull request by ronfife**
Added Pythagorean Theorem files. This is my first contribution on Github. Feedback welcome. Need to do explanation file. Maybe could be put in new directory: geometry/length?

### CODE REVIEW

**Comment by Kyle-P** [comment]
I'll go over this sometime tomorrow. Thanks for your work!

**Comment by Kyle-P** [comment]
This looks good @ronfife! Thanks for the comments and all the changes.

**Comment by ronfife** [comment]
@Kyle-P, I made the changes to PythagoreanCalculator.java as you requested. If it it needs more work, let me know. I'm new to Github and confused about branches. I edited the copy on my branch (I downloaded a copy of your repository to my repository and worked my branch there; I think), then deleted the class file because it was the old one. I can compile and upload the new one, if you want. I found your repository at: https://www.codetriage.com/kyle-p/mathematics after searching hours for something a novice could do in Java.

**Comment by Kyle-P** [comment]
Great! Thanks for all the info @ronfife. The class file isn't necessary. Thanks for considering it though! 

We received all your work fine. In your copy of the repo, after you work on a specific feature in a branch, you "push" that branch in a pull request to the original repo (this one). After the work is merged, you can safely delete the branch on your copy of the repo.

**Pull request merged**
